exclude: "{{cookiecutter.project_slug}}|.github/contributors.json|CHANGELOG.md|CONTRIBUTORS.md"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the latest version
    hooks:
      - id: isort
  # Run scripts/copy_before_commit.sh
  - repo: local
    hooks:
      - id: copy-before-commit
        name: Copy before commit
        entry: scripts/copy_before_commit.sh
        language: script
        types: [python]
        pass_filenames: false
