# Generated by Django 4.2.4 on 2023-08-15 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_post_published"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Blogs",
        ),
        migrations.AlterModelTable(
            name="blogs",
            table="t_blogs",
        ),
    ]
