# Generated by Django 4.2.4 on 2023-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_post_blogs_alter_blogs_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blogs",
            name="unique_post",
        ),
        migrations.RenameField(
            model_name="blogs",
            old_name="create_by",
            new_name="author",
        ),
        migrations.AddConstraint(
            model_name="blogs",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_post"
            ),
        ),
    ]
